# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Inicial(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(578, 334)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(230, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(100, 160, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 160, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Main"))
        self.label.setText(_translate("Frame", "PRINCIPAL"))
        self.pushButton.setText(_translate("Frame", "Cadastrar"))
        self.pushButton_2.setText(_translate("Frame", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Tela_Inicial()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
