# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from cadastro import Cadastro
from pessoa import Pessoa

class Ui_TelaCadastro(object):
    def setupUi(self, TelaCadastro):
        TelaCadastro.setObjectName("TelaCadastro")
        TelaCadastro.resize(656, 488)
        font = QtGui.QFont()
        font.setFamily("Hack")
        TelaCadastro.setFont(font)
        TelaCadastro.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label = QtWidgets.QLabel(TelaCadastro)
        self.label.setGeometry(QtCore.QRect(280, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit.setGeometry(QtCore.QRect(200, 50, 261, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(TelaCadastro)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 90, 261, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(TelaCadastro)
        self.label_3.setGeometry(QtCore.QRect(170, 90, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 130, 261, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(TelaCadastro)
        self.label_4.setGeometry(QtCore.QRect(120, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 170, 261, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(TelaCadastro)
        self.label_5.setGeometry(QtCore.QRect(100, 170, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(TelaCadastro)
        self.pushButton.setGeometry(QtCore.QRect(280, 210, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(TelaCadastro)
        self.label_6.setGeometry(QtCore.QRect(290, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 300, 261, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(TelaCadastro)
        self.label_7.setGeometry(QtCore.QRect(120, 300, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(TelaCadastro)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 300, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(TelaCadastro)
        self.line.setGeometry(QtCore.QRect(7, 240, 641, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_6 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 370, 261, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(TelaCadastro)
        self.label_8.setGeometry(QtCore.QRect(100, 450, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 410, 261, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(TelaCadastro)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 450, 261, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(TelaCadastro)
        self.label_9.setGeometry(QtCore.QRect(150, 370, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(TelaCadastro)
        self.label_10.setGeometry(QtCore.QRect(120, 410, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(TelaCadastro)
        QtCore.QMetaObject.connectSlotsByName(TelaCadastro)

        """modificações"""

        self.cad = Cadastro()
        self.pushButton.clicked.connect(self.botaoCadastra)
        self.pushButton_2.clicked.connect(self.botaoBusca)

    def botaoCadastra(self):
        nome = self.lineEdit.text()
        endereco = self.lineEdit_3.text()
        cpf = self.lineEdit_2.text()
        nascimento = self.lineEdit_4.text()
        if not(nome == '' or endereco == '' or cpf == '' or nascimento == ''):
            p = Pessoa(nome, endereco, cpf, nascimento)
            if(self.cad.cadastra(p)):
                QMessageBox.information(None, 'POOII', 'Cadastro realizado com sucesso!')
                self.lineEdit.setText('')
                self.lineEdit_2.setText('')
                self.lineEdit_3.setText('')
                self.lineEdit_4.setText('')
            else:
                QMessageBox.information(None, 'POOII', 'CPF informado já existe!')
        else:
            QMessageBox.information(None, 'POOII', 'Todas as informações devem ser preenchidas!')


    def botaoBusca(self):
        cpf = self.lineEdit_5.text()
        pessoa = self.cad.busca(cpf)
        if(pessoa != None):
            self.lineEdit_6.setText(pessoa.nome)
            self.lineEdit_7.setText(pessoa.endereco)
            self.lineEdit_8.setText(pessoa.nascimento)
        else:
            QMessageBox.information(None,'POOII', 'CPF não encontrado!')

    def retranslateUi(self, TelaCadastro):
        _translate = QtCore.QCoreApplication.translate
        TelaCadastro.setWindowTitle(_translate("TelaCadastro", "Tela de Cadastro"))
        self.label.setText(_translate("TelaCadastro", "CADASTRO"))
        self.label_2.setText(_translate("TelaCadastro", "NOME"))
        self.label_3.setText(_translate("TelaCadastro", "CPF"))
        self.label_4.setText(_translate("TelaCadastro", "ENDEREÇO"))
        self.label_5.setText(_translate("TelaCadastro", "NASCIMENTO"))
        self.pushButton.setText(_translate("TelaCadastro", "CADASTRAR"))
        self.label_6.setText(_translate("TelaCadastro", "BUSCAR"))
        self.label_7.setText(_translate("TelaCadastro", "CPF"))
        self.pushButton_2.setText(_translate("TelaCadastro", "Buscar"))
        self.label_8.setText(_translate("TelaCadastro", "NASCIMENTO"))
        self.label_9.setText(_translate("TelaCadastro", "NOME"))
        self.label_10.setText(_translate("TelaCadastro", "ENDEREÇO"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaCadastro = QtWidgets.QFrame()
    ui = Ui_TelaCadastro()
    ui.setupUi(TelaCadastro)
    TelaCadastro.show()
    sys.exit(app.exec_())
